version: '3'

services:
  # Сервис с базой данных PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"

  # Сервис с ботом
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE: ${DATABASE}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
    depends_on:
      - postgres
